spring:
  application:
    name: item-service
    
#server:
#88888888888888888
#666666666666   
#7777777777777777
#  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
---
spring:
  profiles: item1
    #烧烤萨芬尽快哈框架鲨科技的
    #数据库哈弗看见啥肯定是减肥
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002
